/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AppRouteImport } from './routes/app'
import { Route as AfiliadosRouteImport } from './routes/afiliados'
import { Route as AfiliadoRouteImport } from './routes/afiliado'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedImpulsionamentoRouteImport } from './routes/_authenticated/impulsionamento'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const AfiliadosRoute = AfiliadosRouteImport.update({
  id: '/afiliados',
  path: '/afiliados',
  getParentRoute: () => rootRouteImport,
} as any)
const AfiliadoRoute = AfiliadoRouteImport.update({
  id: '/afiliado',
  path: '/afiliado',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedImpulsionamentoRoute =
  AuthenticatedImpulsionamentoRouteImport.update({
    id: '/impulsionamento',
    path: '/impulsionamento',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/afiliado': typeof AfiliadoRoute
  '/afiliados': typeof AfiliadosRoute
  '/app': typeof AppRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/impulsionamento': typeof AuthenticatedImpulsionamentoRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/afiliado': typeof AfiliadoRoute
  '/afiliados': typeof AfiliadosRoute
  '/app': typeof AppRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/impulsionamento': typeof AuthenticatedImpulsionamentoRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/afiliado': typeof AfiliadoRoute
  '/afiliados': typeof AfiliadosRoute
  '/app': typeof AppRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/impulsionamento': typeof AuthenticatedImpulsionamentoRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/afiliado'
    | '/afiliados'
    | '/app'
    | '/auth'
    | '/reset-password'
    | '/sitemap.xml'
    | '/admin'
    | '/impulsionamento'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/afiliado'
    | '/afiliados'
    | '/app'
    | '/auth'
    | '/reset-password'
    | '/sitemap.xml'
    | '/admin'
    | '/impulsionamento'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/afiliado'
    | '/afiliados'
    | '/app'
    | '/auth'
    | '/reset-password'
    | '/sitemap.xml'
    | '/_authenticated/admin'
    | '/_authenticated/impulsionamento'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AfiliadoRoute: typeof AfiliadoRoute
  AfiliadosRoute: typeof AfiliadosRoute
  AppRoute: typeof AppRoute
  AuthRoute: typeof AuthRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/afiliados': {
      id: '/afiliados'
      path: '/afiliados'
      fullPath: '/afiliados'
      preLoaderRoute: typeof AfiliadosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/afiliado': {
      id: '/afiliado'
      path: '/afiliado'
      fullPath: '/afiliado'
      preLoaderRoute: typeof AfiliadoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/impulsionamento': {
      id: '/_authenticated/impulsionamento'
      path: '/impulsionamento'
      fullPath: '/impulsionamento'
      preLoaderRoute: typeof AuthenticatedImpulsionamentoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedImpulsionamentoRoute: typeof AuthenticatedImpulsionamentoRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedImpulsionamentoRoute: AuthenticatedImpulsionamentoRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AfiliadoRoute: AfiliadoRoute,
  AfiliadosRoute: AfiliadosRoute,
  AppRoute: AppRoute,
  AuthRoute: AuthRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
